// Generate NativeWind variables from the same palette used by React Native.
const fs = require('node:fs');
const path = require('node:path');
const tokens = require('../src/constants/theme-tokens.json');
const target = path.join(__dirname, '../src/global.css');

function hsl(hex) {
  const [r, g, b] = hex.slice(1).match(/../g).map((part) => parseInt(part, 16) / 255);
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const delta = max - min, lightness = (max + min) / 2;
  let hue = 0;
  if (delta) {
    if (max === r) hue = ((g - b) / delta) % 6;
    else if (max === g) hue = (b - r) / delta + 2;
    else hue = (r - g) / delta + 4;
    hue = (hue * 60 + 360) % 360;
  }
  const saturation = delta ? delta / (1 - Math.abs(2 * lightness - 1)) : 0;
  return `${hue.toFixed(3)} ${(saturation * 100).toFixed(3)}% ${(lightness * 100).toFixed(3)}%`;
}

const current = fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n');
const prefix = current.split('@layer base')[0];
const blocks = Object.entries(tokens).map(([mode, colors]) => {
  const variables = Object.entries(colors).map(([key, value]) => {
    const name = key.replace(/([a-z])([A-Z0-9])/g, '$1-$2').toLowerCase();
    return `    --${name}: ${hsl(value)};`;
  });
  variables.push('    --radius: 0.625rem;');
  return `  ${mode === 'light' ? ':root' : '.dark:root'} {\n${variables.join('\n')}\n  }`;
});
const output = `${prefix}@layer base {\n  /* Generated by npm run theme:generate. Edit src/constants/theme-tokens.json. */\n${blocks.join('\n\n')}\n}\n`;
if (process.argv.includes('--check')) {
  if (current !== output) {
    console.error('Theme CSS is stale. Run npm run theme:generate.');
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(target, output);
}
